version: "3.9"

networks:
  app-tier:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment: 
      - ALLOW_ANONYMOUS_LOGIN=yes
    hostname: zookeeper-server
    networks:
      - app-tier
  kafka:
    image: 'bitnami/kafka:latest'
    environment: 
       - ALLOW_PLAINTEXT_LISTENER=yes 
       - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
    ports:
      - "9092:9092"
    hostname: kafka-server
    networks:
      - app-tier
  syslog-producer:
    image: 'elodina/syslog-kafka'
    command: --topic syslog --broker.list kafka-server:9092
    hostname: syslog
    ports:
      - "5140:5140"
    networks:
      - app-tier
